# Add nodejs v16.14.2 and npm v7.6.0
FROM node:16.14.2-alpine as node

# Set master image
FROM rajeshisnepali/gitlab-ci-initial

LABEL maintainer="Rajesh Chaudhary rajeshisnepali@gmail.com"

# Set working directory
WORKDIR /var/www

# Install node16
COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

# Remove Cache
RUN rm -rf /var/cache/apk/*

# CMD ["tail", "-f", "/dev/null"]
CMD ["node"]
